---
# TASK [roles/applications/hyper : Ensure Hyper is installed] ********************
# An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: Could not open: /tmp/ansible-tmp-1638754370.8117645-108328-115190064878693/rpmsu1f37rq
# fatal: [workstation]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible-tmp-1638754370.8117645-108328-115190064878693/AnsiballZ_dnf.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/tmp/ansible-tmp-1638754370.8117645-108328-115190064878693/AnsiballZ_dnf.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/ansible-tmp-1638754370.8117645-108328-115190064878693/AnsiballZ_dnf.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.dnf', init_globals=dict(_module_fqn='ansible.modules.dnf', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.10/runpy.py\", line 209, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_dnf_payload_wnieu2hu/ansible_dnf_payload.zip/ansible/modules/dnf.py\", line 1427, in <module>\n  File \"/tmp/ansible_dnf_payload_wnieu2hu/ansible_dnf_payload.zip/ansible/modules/dnf.py\", line 1416, in main\n  File \"/tmp/ansible_dnf_payload_wnieu2hu/ansible_dnf_payload.zip/ansible/modules/dnf.py\", line 1390, in run\n  File \"/tmp/ansible_dnf_payload_wnieu2hu/ansible_dnf_payload.zip/ansible/modules/dnf.py\", line 1048, in ensure\n  File \"/tmp/ansible_dnf_payload_wnieu2hu/ansible_dnf_payload.zip/ansible/modules/dnf.py\", line 948, in _install_remote_rpms\n  File \"/usr/lib/python3.10/site-packages/dnf/base.py\", line 1272, in add_remote_rpms\n    raise IOError(_(\"Could not open: {}\").format(' '.join(pkgs_error)))\nOSError: Could not open: /tmp/ansible-tmp-1638754370.8117645-108328-115190064878693/rpmsu1f37rq\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
- name: "Ensure {{ app_name }} is installed"
  dnf:
    name: "{{ hyper_rpm_url }}"
    state: "{{ app_state | default('present') }}"

- name: Ensure Fira Code font is installed
  include_role:
    name: helpers/fontinstall
  vars:
    fonts:
      - fira code
  when: install_fira_code
